# Generated by Django 2.2.16 on 2022-07-26 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220726_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Рейтинг вычисляется на основании score отзывов', null=True, validators=[django.core.validators.MaxValueValidator(10, 'Максимальная оценка - 10'), django.core.validators.MinValueValidator(1, 'Минимальная оценка - 1')], verbose_name='Рейтинг произведения'),
        ),
    ]
